# SPDX-FileCopyrightText: Octavia Togami <octy@octyl.net>
# SPDX-License-Identifier: CC0-1.0

[libraries]
junit-jupiter = "org.junit.jupiter:junit-jupiter:6.0.1"
intellij-annotations = "org.jetbrains:annotations:26.0.2-1"
truth = "com.google.truth:truth:1.4.5"
